# Generated by Django 3.2.16 on 2023-05-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_auto_20230410_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ('output_order', 'title'), 'verbose_name': 'мороженое', 'verbose_name_plural': 'Мороженое'},
        ),
    ]
